---
- name: Create RHCHOS image
  hosts: localhost
  roles:
    - rhcos_create_image

- name: Intel worker flavor create
  hosts: localhost
  roles:
    - custom_flavor_create

- name: Loop over virtual machine create role in the playbook with dynamic variable names
  hosts: localhost
  vars:
    iterations: 3  # Number of iterations for the loop
  tasks:
    - name: Virtual machine create role in loop
      ansible.builtin.include_role:
        name: vm_create
      loop: "{{ range(0, iterations) | list }}"
      loop_control:
        loop_var: iteration
      vars:
        vm_create_name: "rdr-mac-worker-openstack-{{ iteration }}"
        vm_create_worker_hostname: "rdr-mac-worker-openstack-{{ iteration }}"

- name: Approve and issue
  hosts: localhost
  roles:
    - csr_approve
  vars:
    csr_approve_intel_count: 3

- name: Intel worker vitrual_machine create
  hosts: localhost
  roles:
    - vm_action
  vars:
    vm_action_name: stop

- name: Intel worker vitrual_machine create
  hosts: localhost
  roles:
    - vm_action
  vars:
    vm_action_name: start
