---
- name: OpenStack worker node configuration Tasks
  hosts: all
  tasks:
    - name: Intel worker vitrual_machine delete
      roles:
        - vm-delete

    - name: Intel worker flavor create
      roles:
        - flavor-delete

    - name: Create RHCHOS image
      hosts: all
      roles:
        - rhcosImage-delete
