---
- name: OpenStack worker node configuration Tasks
  hosts: all
  tasks:
    - name: Create RHCHOS image
      roles:
        - rhcosImage-create

    - name: Intel worker flavor create
      roles:
        - flavor-create

    - name: Intel worker vitrual_machine create
      roles:
        - vm-create

    - name: Intel worker vitrual_machine create
      roles:
        - vm-server-action
      vars:
        virtual_machine_server_action: stop

    - name: Intel worker vitrual_machine create
      roles:
        - vm-server-action
      vars:
        virtual_machine_server_action: start
