---
- name: Intel worker vitrual_machine delete
  hosts: localhost
  roles:
    - virtual_machine_delete

- name: Intel worker flavor create
  hosts: localhost
  roles:
    - custom_flavor_delete

- name: Create RHCHOS image
  hosts: localhost
  roles:
    - rhcos_delete_image
