---
- name: Create RHCHOS image
  hosts: localhost
  roles:
    - rhcos_create_image

- name: Intel worker flavor create
  hosts: localhost
  roles:
    - custom_flavor_create

- name: Loop over virtual machine create role in the playbook with dynamic variable names
  hosts: localhost
  vars:
    iterations: "{{ virtual_machine_create_count }}"  # Number of iterations for the loop
  tasks:
    - name: Virtual machine create role in loop
      ansible.builtin.include_role:
        name: virtual_machine_create
      loop: "{{ range(1, iterations + 1) | list }}"
      loop_control:
        loop_var: iteration
      vars:
        virtual_machine_create_name: "rdr-mac-worker-openstack-{{ iteration }}"
        virtual_machine_create_worker_hostname: "rdr-mac-worker-openstack-{{ iteration }}"

- name: Approve and issue
  hosts: localhost
  roles:
    - approve_and_issue

- name: Intel worker vitrual_machine create
  hosts: localhost
  roles:
    - virtual_machine_action
  vars:
    virtual_machine_action_name: stop

- name: Intel worker vitrual_machine create
  hosts: localhost
  roles:
    - virtual_machine_action
  vars:
    virtual_machine_action_name: start
