---
- name: Get virtual machine info
  openstack.cloud.server_info:
    cloud: openstack
    name: "{{ vm_create_name }}"
  register: vm_info
  until: vm_info.servers[0].status == "ACTIVE"
  retries: 60
  delay: 10

- name: Print virtual machine vm_info
  ansible.builtin.debug:
    var: vm_info
