---
- name: OpenStack worker node configuration Tasks (i.e. Create worker.ign, Upload RHCOS Image, Create Customization Script, Create Instance etc)
  hosts: all
  vars_files:
    - ../../../../vars/main.yml

  tasks:
    - name: Create host aggregate (host group) to openstack
      openstack.cloud.host_aggregate:
        cloud: openstack
        state: present
        name: "{{ host_aggregate_name }}"
        hosts: "{{ host_name_list }}"
        metadata:
          availability_zone: "{{ host_availability_zone_name }}"
