---
# Virtual_machine details
virtual_machine_create_name: rdr-mac-worker-openstack
virtual_machine_create_region_name: RegionOne
virtual_machine_create_availability_zone: Test
virtual_machine_create_image_name: 4df699b6-6877-4b77-9ddb-0d6dc9cefb68
virtual_machine_create_flavor: "m1.medium"
virtual_machine_create_volume_size: 80
virtual_machine_create_keypair_name: pun_keypair
virtual_machine_create_network_name: provider
virtual_machine_create_userdata: "{{ lookup('template', 'worker-amd64.ign.j2') }}"
virtual_machine_create_timeout: 300
virtual_machine_create_count: 3

# Used in ignition task
virtual_machine_create_worker_hostname: "rdr-mac-worker-openstack"
virtual_machine_create_worker_hostname_encoded: ""
virtual_machine_create_etc_resolve_encoded: ""
virtual_machine_create_dns_none_encoded: ""
virtual_machine_create_bastion_ip: "10.20.181.69"
virtual_machine_create_domain_name: "rdr-mac1"
virtual_machine_create_http_port: "8080"
virtual_machine_create_https_port: "443"

# Ignition Files
virtual_machine_create_dns_none_conf: |-
  [main]
  dns=none
