---
# Virtual_machine details
virtual_machine_create_name: rdr-mac-worker
virtual_machine_create_region_name: RegionOne
virtual_machine_create_availability_zone: Test
virtual_machine_create_image_name: 0c4d9ba3-ed14-403a-a35d-8b4c9f720f1f
virtual_machine_create_flavor: "PUN_custom_flavor"
virtual_machine_create_volume_size: 80
virtual_machine_create_keypair_name: pun_keypair
virtual_machine_create_network_name: provider
virtual_machine_create_userdata: "#!/bin/sh\nyum -y install python3"
# virtual_machine_userdata: "|\n#cloud-config\nchpasswd:\nlist: |\nubuntu:passw0rd\nexpire: False\npackages:\n- ansible\npackage_upgrade: true"
# Examples:
#       userdata: |
#         #cloud-config
#         chpasswd:
#           list: |
#             ubuntu:{{ default_password }}
#           expire: False
#         packages:
#           - ansible
#         package_upgrade: true
virtual_machine_create_timeout: 300
