---

# Image details centos
image_name_centos: Centos9_img
image_container_format_centos: bare
image_disk_format_centos: qcow2
image_dest_filename_centos: /tmp/CentOS-Stream-GenericCloud-9-20230327.0.x86_64.qcow2
image_is_public_centos: true
image_url_centos: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-20230327.0.x86_64.qcow2
image_cpu_arch_centos: x86_64
image_distro_centos: rhel
image_validate_certs_centos: false
