# Update the Chrony config based on input subnet/s information
---
- name: Print the supplied subnets
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ subnets }}"

- name: Backup the prior Chrony configuration
  ansible.builtin.shell:
    cmd: |
      mv /etc/chrony.conf.backup /etc/chrony.conf.backup-$(date +%s) || true
      cp -f /etc/chrony.conf /etc/chrony.conf.backup

- name: Conditionally add allow subnet in chrony.conf [If supplied subnet list != ""]
  ansible.builtin.include_tasks: update-chrony-subnet.yml
  loop: "{{ subnets }}"
  when: (item | length) != 0

- name: Restart chronyd.service
  ansible.builtin.systemd_service:
    name: chronyd.service
    state: restarted
