# Update the Chrony config
---
- name: Generate the subnet list
  ansible.builtin.shell: |
    set -o pipefail
    ip r | grep -v default | awk '{print $1}'
  register: subnet_list

- name: Print the subnets
  ansible.builtin.debug:
    var: subnet_list.stdout_lines

- name: Backup the prior Chrony configuration
  ansible.builtin.shell:
    cmd: |
      mv /etc/chrony.conf.backup /etc/chrony.conf.backup-$(date +%s) || true
      cp -f /etc/chrony.conf /etc/chrony.conf.backup

- name: Conditionally add allow subnet in chrony.conf
  ansible.builtin.include_tasks: update-chrony-subnet.yml
  loop: "{{ subnet_list.stdout_lines }}"

- name: Restart chronyd.service
  ansible.builtin.systemd_service:
    name: chronyd.service
    state: restarted
