---
# Virtual machine action
virtual_machine_server_action: start
# server action list
# "lock"
# "pause"
# "reboot_hard"
# "reboot_soft"
# "rebuild"
# "resume"
# "shelve"
# "shelve_offload"
# "start"
# "stop"
# "suspend"
# "unlock"
# "unpause"
# "unshelve"
virtual_machine_action_timeout: 200
virtual_machine_action_wait: true
