---
# Host aggregate details
host_aggregate_create_name: multi-arch-compute-aggregate
host_aggregate_create_availability_zone_name: multi-arch-aggregate
host_aggregate_create_name_list: [<host1>, <host2>, <host3>]
# Examples:
# host_name_list: ["xcloud8", "xcloud7", "xcloud10"]
